### PR TITLE
Added several Unit Tests.

### PR DESCRIPTION
**Pull request by TheRealHaui**
I've added several Unit Tests and want to contribute them to the project.

### CODE REVIEW

**Comment by TheRealHaui** [comment]
Hi @struberg,
I saw you have the right to commit.
Would you mind reviewing and confirming my contribution?
Thanks in advance.

**Comment by struberg** [comment]
Hi! Yes, will check - thanks!
I'll review and comment on github first, ok?

**Comment by TheRealHaui** [comment]
@struberg 
Sure, of course.
Was my assumption that this happens on Github.
Thanks.

Beside that I'd like to mention that I am not so experienced with the implicit rules on Github yet.
Therefore I thought it is a good idea to ask a specific person via a comment to review and confirm the contribution.
I hope this is allright.

**Comment by TheRealHaui** [comment]
@struberg 
Do you need any additional information?

**Pull request closed without merging**
