### PR TITLE
Allow InterceptionFactory to have an interface as parameter

### PR DESCRIPTION
**Pull request by kalgon**
See https://issues.jboss.org/browse/CDI-686

### CODE REVIEW

**Comment by tandraschko** [comment]
@struberg @rmannibucau 
it's now implemented by weld:

> You can now use InterceptionFactory with an interface as a parameter (WELD-2550, WELD-2533)
    This means the proxy class will be based off an interface which is by definition always proxyable
    You can therefore even supply an unproxyable implementation and it will still work
    Note that this is experimental feature with some limitations to it, see Weld docs for more details


https://issues.jboss.org/browse/WELD-2550
https://issues.jboss.org/browse/WELD-2533

should we apply it?

**Comment by rmannibucau** [comment]
@tandraschko we should review our behavior and weld one, probably test a few more cases (like default methods) but otherwise +1 to get it asap

**Comment by tandraschko** [comment]
Could you maybe describe some tests you would do - so @kalgon could add it?

**Comment by rmannibucau** [comment]
Sure, out of my head:

1. no interceptor on the interface
2. interceptors on the interface
3. 1 + configured bindings programmatically
4. 2 + configured bindings programmatically
5. default method handling

Guess it can be enough to merge and be secured enough it works for common use cases. Wdyt?

**Comment by kalgon** [comment]
@tandraschko I am on it but I have a weird problem. When simply producing a bean based on an interface which has interceptor bindings already, it is proxied and intercepted without needing to use the InterceptionFactory. And when I explicitly create an intercepted instance with the IF, my bean gets intercepted twice...

**Comment by rmannibucau** [comment]
@kalgon yes, we always supported interceptors on producers in OWB cause it was too limiting to not do it in CDI < 2.0, there is a flag to switch it off in openwebbeans.properties but i'd recommand to keep it and just ignore it if the instance was created from interception factory.

**Comment by kalgon** [comment]
@rmannibucau I had to check if the produced instance is an `OwbInterceptorProxy` in `AbstractProducer` to avoid intercepting twice. I hope this was the correct way to fix it.

**Comment by rmannibucau** [comment]
@kalgon exactly what I had in mind
@struberg want to give a look too? otherwise @tandraschko it looks good to me

**Comment by tandraschko** [comment]
it's fine for me
lets wait about marks feedback

**Comment by tandraschko** [comment]
@struberg do you have write access to merge the PR then? 
I still can't. Didn't we migrate to gitbox already?

**Comment by rmannibucau** [comment]
@tandraschko add github as a remote and fetch+merge the branch, it is simpler

**Comment by tandraschko** [comment]
simpler as a simple "merge" button here? :D not really.
Not sure but it works fine in MyFaces.

**Comment by kalgon** [comment]
Hello, is there anything else needed I can help with to merge this PR?
If I am not mistaken, I don't think this change has made it to the SVN repository.

**Comment by tandraschko** [comment]
I will take care of it today

**Comment by tandraschko** [comment]
Applied it, thank you very much!
Please verify it in our svn and close the PR.

**Comment by kalgon** [comment]
Looks good to me. Thanks!

**Pull request closed without merging**
